UPLOAD_FOLDER = './static/img/upload'
ALLOWED_EXTENSIONS = set(['jpg', 'jpeg','png'])

# SENTIMENT
POSITIVE = "POSITIVE"
NEGATIVE = "NEGATIVE"
NEUTRAL = "NEUTRAL"
SENTIMENT_THRESHOLDS = (0.4, 0.7)

# Twitter
CONSUMER_KEY = '3S4jDZOBEi3hIqFpGQaQUFeaB'
CONSUMER_SECRET = '7RmfGfbJs5DSGGunq0caA6DxUUwM2hrZisS716rTYyzyv7DmJr'
ACCESS_TOKEN_KEY = '37399666-Hb5AwC9LzoJmEYLND35aN27Xx6zXtUCUmoxLquDDM'
ACCESS_TOKEN_SECRET = 'G9WSaoMtOGqr7JI3McCUB1yjQPDpYNkkiUspQkNmXS7Uc'

# mysql
mysqlcs="mysql+pymysql://root:mysql57515c@localhost:3306/twitter"