CREATE SCHEMA IF NOT EXISTS `twitter` DEFAULT CHARACTER SET latin1 

CREATE TABLE IF NOT EXISTS `twitter`.`tweets` (
 `id` INT(11) NOT NULL AUTO_INCREMENT,
 `tweet` VARCHAR(250) NOT NULL,
 `tweetsentiment` VARCHAR(10) NOT NULL,
 `imagename` VARCHAR(45) NULL DEFAULT NULL,
 `imagetypeCifar` VARCHAR(100) NULL DEFAULT NULL,
 `imagetypeXception` VARCHAR(100) NULL DEFAULT NULL,
 `facialEmotion` VARCHAR(100) NULL DEFAULT NULL,
 PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = latin1